# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

masked_approximation_impl <- function(U, d, V, row, col) {
    .Call(`_LRMF3_masked_approximation_impl`, U, d, V, row, col)
}

